//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLIBRARYEntities : DbContext
    {
        public DBLIBRARYEntities()
            : base("name=DBLIBRARYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLAUTHOR> TBLAUTHOR { get; set; }
        public virtual DbSet<TBLBOOK> TBLBOOK { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLEMPLOYEE> TBLEMPLOYEE { get; set; }
        public virtual DbSet<TBLMEMBERS> TBLMEMBERS { get; set; }
        public virtual DbSet<TBLMOVE> TBLMOVE { get; set; }
        public virtual DbSet<TBLPUNISHMENT> TBLPUNISHMENT { get; set; }
        public virtual DbSet<TBLTILL> TBLTILL { get; set; }
    }
}
