//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMOVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMOVE()
        {
            this.TBLPUNISHMENT = new HashSet<TBLPUNISHMENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<byte> EMPLOYEE { get; set; }
        public Nullable<System.DateTime> PURCHASEDATE { get; set; }
        public Nullable<System.DateTime> ISSUEDATE { get; set; }
        public Nullable<System.DateTime> GETMEMBERDATE { get; set; }
        public Nullable<bool> PROCESSSITUATION { get; set; }
    
        public virtual TBLBOOK TBLBOOK { get; set; }
        public virtual TBLEMPLOYEE TBLEMPLOYEE { get; set; }
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPUNISHMENT> TBLPUNISHMENT { get; set; }
    }
}
