//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPUNISHMENT
    {
        public int ID { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public Nullable<int> MOVE { get; set; }
    
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
        public virtual TBLMEMBERS TBLMEMBERS1 { get; set; }
        public virtual TBLMOVE TBLMOVE { get; set; }
    }
}
